### PR TITLE
Fix missing package dependencies for scoped packages

### LINKED ISSUE #498: Generated package.json missing package dependencies for scoped packages
I did some investigating myself because I really need https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27729 to get resolved.

The bug occurs when types for a scoped package contain dependencies on other scoped packages. When collecting the dependencies for a generated `package.json` here...
https://github.com/Microsoft/types-publisher/blob/745ed6d124dbb5c8e755beb2aa88130b988c9c62/src/lib/package-generator.ts#L74

...it walks over the dependencies specified by the typing...
https://github.com/Microsoft/types-publisher/blob/745ed6d124dbb5c8e755beb2aa88130b988c9c62/src/lib/package-generator.ts#L114

...but when calling `allPackages.hasTypingFor`, the argument contains the scoped (unmangled) package name but it expects a mangled package name when called here...

https://github.com/Microsoft/types-publisher/blob/745ed6d124dbb5c8e755beb2aa88130b988c9c62/src/lib/package-generator.ts#L122

...therefore not adding the dependency because for example calling `allPackages.hasTypingFor("@babel/template")` will return `false` but `allPackages.hasTypingFor("babel__template")` return will return `true`.

~~I did not create a PR because I do not have a good enough understanding of the codebase but if it's a simple change I can still make one if requested.~~ I gave it a try anyway. See referenced PR.

### PR DESCRIPTION
**Pull request by mgroenhoff**
This fixes #498 and produces the following changes in generated packages:

```
File: autobind-decorator\package.json

File: babel__core\package.json
        "@babel/types": "^7.0.0" <>         "@babel/types": "^7.0.0",
                                            "@types/@babel/generator": "*",
                                            "@types/@babel/template": "*",
                                            "@types/@babel/traverse": "*"
---------------------------------------------------------------------------

File: egjs__axes\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@egjs/component": "*"
                               },
----------------------------------------------------------------

File: ember\package.json
        "@types/handlebars": "*",                 <>         "@types/@ember/application": "*",
        "@types/rsvp": "*",                                  "@types/@ember/array": "*",
        "@types/htmlbars-inline-precompile": "*",            "@types/@ember/component": "*",
                                                             "@types/@ember/controller": "*",
        "@types/jquery": "*",                                "@types/@ember/debug": "*",
        "@types/ember__string": "*",                         "@types/@ember/engine": "*",
                                                             "@types/@ember/error": "*",
                                                             "@types/@ember/object": "*",
        "@types/ember__polyfills": "*",                      "@types/@ember/polyfills": "*",
                                                             "@types/@ember/routing": "*",
                                                             "@types/@ember/runloop": "*",
                                                             "@types/@ember/service": "*",
                                                             "@types/@ember/string": "*",
        "@types/ember__object": "*",                         "@types/@ember/test": "*",
        "@types/ember__utils": "*",                          "@types/@ember/utils": "*",
                                                             "@types/ember__application": "*",
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
        "@types/ember__engine": "*",              <>         "@types/ember__component": "*",
                                                             "@types/ember__controller": "*",
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
        "@types/ember__runloop": "*",             <>         "@types/ember__engine": "*",
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
        "@types/ember__controller": "*",          <>         "@types/ember__object": "*",
        "@types/ember__component": "*",                      "@types/ember__polyfills": "*",
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
        "@types/ember__application": "*",         <>         "@types/ember__runloop": "*",
                                                             "@types/ember__service": "*",
                                                             "@types/ember__string": "*",
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
        "@types/ember__service": "*"              <>         "@types/ember__utils": "*",
                                                             "@types/handlebars": "*",
                                                             "@types/htmlbars-inline-precompile": "*",
                                                             "@types/jquery": "*",
                                                             "@types/rsvp": "*"
------------------------------------------------------------------------------------------------------

File: ember__application\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/application": "*",
                                   "@types/@ember/engine": "*",
                                   "@types/@ember/object": "*",
                                   "@types/@ember/routing": "*"
                               },
--------------------------------------------------------------------

File: ember__array\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/array": "*",
                                   "@types/@ember/object": "*"
                               },
--------------------------------------------------------------

File: ember__component\package.json
 -+         "@types/@ember/component": "*",
            "@types/@ember/object": "*",
-------------------------------------------

File: ember__controller\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/object": "*"
                               },
--------------------------------------------------------------

File: ember__debug\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/debug": "*",
                                   "@types/@ember/engine": "*",
                                   "@types/@ember/object": "*"
                               },
---------------------------------------------------------------

File: ember__engine\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/engine": "*",
                                   "@types/@ember/object": "*"
                               },
---------------------------------------------------------------

File: ember__object\package.json
 -+         "@types/@ember/object": "*",
----------------------------------------

File: ember__routing\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/component": "*",
                                   "@types/@ember/controller": "*",
                                   "@types/@ember/object": "*",
                                   "@types/@ember/routing": "*",
                                   "@types/@ember/service": "*"
                               },
-------------------------------------------------------------------

File: ember__runloop\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/runloop": "*"
                               },
---------------------------------------------------------------

File: ember__service\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/object": "*"
                               },
--------------------------------------------------------------

File: ember__test\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@ember/application": "*"
                               },
-------------------------------------------------------------------

File: ember__test-helpers\package.json
        "@types/htmlbars-inline-precompile": "*", <>         "@types/@ember/application": "*",
                                                             "@types/@ember/error": "*",
-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
        "@types/ember__error": "*"                <>         "@types/ember__error": "*",
                                                             "@types/htmlbars-inline-precompile": "*"
-----------------------------------------------------------------------------------------------------

File: ember-data\package.json
 -+         "@types/@ember/object": "*",
----------------------------------------

File: feathersjs__authentication\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@feathersjs/authentication": "*",
                                   "@types/@feathersjs/feathers": "*"
                               },
----------------------------------------------------------------------------

File: feathersjs__authentication-client\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@feathersjs/authentication-client": "*"
                               },
----------------------------------------------------------------------------------

File: feathersjs__authentication-jwt\package.json
 -+         "@types/@feathersjs/authentication-jwt": "*",
            "@types/@feathersjs/feathers": "*",
---------------------------------------------------------

File: feathersjs__authentication-local\package.json
 -+         "@types/@feathersjs/authentication-local": "*",
            "@types/@feathersjs/feathers": "*",
-----------------------------------------------------------

File: feathersjs__authentication-oauth1\package.json
 -+         "@types/@feathersjs/authentication-oauth1": "*",
            "@types/@feathersjs/feathers": "*",
------------------------------------------------------------

File: feathersjs__authentication-oauth2\package.json
 -+         "@types/@feathersjs/authentication-oauth2": "*",
            "@types/@feathersjs/feathers": "*",
------------------------------------------------------------

File: feathersjs__configuration\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@feathersjs/feathers": "*"
                               },
---------------------------------------------------------------------

File: feathersjs__express\package.json
 -+         "@types/@feathersjs/express": "*",
            "@types/@feathersjs/feathers": "*",
-----------------------------------------------

File: feathersjs__feathers\package.json
 -+         "@types/@feathersjs/feathers": "*",
-----------------------------------------------

File: feathersjs__socket-commons\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@feathersjs/feathers": "*"
                               },
---------------------------------------------------------------------

File: ledgerhq__hw-transport-node-hid\package.json
                                <>         "@types/@ledgerhq/hw-transport": "*",
        "@types/node-hid": "*",            "@types/node": "*",
        "@types/node": "*"                 "@types/node-hid": "*"
--------------------------------------------------------------------------------

File: ledgerhq__hw-transport-u2f\package.json
 -+         "@types/@ledgerhq/hw-transport": "*",
-------------------------------------------------

File: lingui__react\package.json
 -+         "@types/@lingui/core": "*",
---------------------------------------

File: storybook__addon-a11y\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@storybook/react": "*"
                               },
-----------------------------------------------------------------

File: storybook__addon-backgrounds\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@storybook/react": "*"
                               },
-----------------------------------------------------------------

File: storybook__addon-centered\package.json
 -+         "@types/@storybook/react": "*",
-------------------------------------------

File: storybook__addon-info\package.json
 -+         "@types/@storybook/react": "*",
-------------------------------------------

File: storybook__addon-jest\package.json
    "dependencies": {}, <>     "dependencies": {
                                   "@types/@storybook/react": "*"
                               },
-----------------------------------------------------------------

File: storybook__addon-knobs\package.json
 -+         "@types/@storybook/react": "*",
-------------------------------------------

File: storybook__addon-notes\package.json
 -+         "@types/@storybook/react": "*",
-------------------------------------------

File: storybook__addon-storyshots\package.json
        "@types/react": "*",    <>         "@types/@storybook/react": "*",
        "@types/puppeteer": "*"            "@types/puppeteer": "*",
                                           "@types/react": "*"
--------------------------------------------------------------------------

File: storybook__react-native\package.json
 -+         "@types/@storybook/react": "*",
-------------------------------------------

File: storybook-addon-jsx\package.json
 -+         "@types/@storybook/react": "*",
-------------------------------------------
```

### CODE REVIEW

**Comment by andy-ms** [comment]
Thanks!

**Comment by mgroenhoff** [comment]
I've noticed that wrong package names are being used when adding dependencies like `@types/@storybook/react`. I'll look into this.

**Comment by mgroenhoff** [comment]
@andy-ms Can you revert and re-open this for now?

**Comment by andy-ms** [comment]
I think it will be easier to make a new pull request for the corrected version.

**Pull request merged**
