### PR TITLE
Add glaze and treat to dependenciesWhitelist

### PR DESCRIPTION
**Pull request by kripod**
Required for seamless augmentation of React attributes, in order to add the `sx` prop for any element: https://github.com/kripod/glaze/pull/16#issuecomment-616528041

### CODE REVIEW

**Comment by kripod** [comment]
Thank you!

I’ll try my best to fix `@types/babel-plugin-glaze` as soon as possible. :blush:

**Comment by sandersn** [comment]
It's actually not published yet -- we're on the middle of moving to a monorepo so some previously-automated things are disconnected.

I'll update this thread when things are ready to go.

**Comment by sandersn** [comment]
OK, DefinitelyTyped/DefinitelyTyped#44048 should be ready to update (or close/open if no updates are needed).

I had to copy this commit over to the new monorepo since the npm publisher needs it too.

In the future, the monorepo will publish a separate package for DT's CI, but that's not done yet. @andrewbranch is on it though.

**Comment by kripod** [comment]
Thank you for being so proactive, adding support so fast!

**Pull request merged**
