### PR TITLE
Added mysql to dependenciesWhitelist.txt 

### PR DESCRIPTION
**Pull request by move-zig**
for use in promise-mysql typings

### CODE REVIEW

**Comment by andy-ms** [comment]
`mysql` doesn't seem to come bundled with typings.
There is a `@types/mysql`. If you want to depend on that you don't need a `package.json` at all, just import it.

**Comment by move-zig** [comment]
I believe this is needed for my pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21290 to solve issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21100.

**Comment by andy-ms** [comment]
`mysql` doesn't provide its own types. It doesn't make sense to depend on it. You should remove the `package.json` from that pull request.

**Comment by move-zig** [comment]
@andy-ms Thanks!

**Pull request closed without merging**
