### PR TITLE
Add validate script

### PR DESCRIPTION
**Pull request by mhegazy**

### CODE REVIEW

**Comment by andy-ms** [comment]
The output of `deleteDirectory` is not used. It could probably just throw an error in that case.

**Comment by andy-ms** [comment]
It looks like every DefinitelyTyped 2.0 project sets noImplicitAny to true, so should be safe to turn that on in these tests.

**Comment by andy-ms** [comment]
This should eventually be integrated into `full.ts`, but right now it's too slow. In the future we should have a version of this that only tests the packages we're about to publish.

**Comment by andy-ms** [comment]
Otherwise, :+1:

**Comment by andy-ms** [comment]
Also, please mention this in the README

**Comment by RyanCavanaugh** [comment]
:+1:

**Comment by mhegazy** [comment]
made it run multiple packages at a time, and accept command line options.

**Pull request merged**
