### PR TITLE
Add script to fix all non-gzipped packages

### PR DESCRIPTION
**Pull request by andy-ms**
We always gzip as of #104 but some packages are still non-gzipped. This would republish them.
Running this requires using the `--forceUpdate` option during `calculate-versions`.
This doesn't necessarily need to be merged, since it only needs to be run once.
Should fix DefinitelyTyped/DefinitelyTyped#10508 and DefinitelyTyped/DefinitelyTyped#10506.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by andy-ms** [comment]
Original version was wrong: the final uploading of `versions.json` would have needlessly updated many packages that we weren't republishing. Fixed to move the check to the calculate-versions step, then we can just publish normally.

**Comment by andy-ms** [comment]
Ran the script. Shall I delete this branch?

**Comment by RyanCavanaugh** [comment]
Not quite sure what's going on here, can you explain in person?

**Comment by mmckenziedev** [comment]
@andy-ms @RyanCavanaugh Did this fix ever get merged? I still experience this issue in my private npm registry proxy.

According to this [NEXUS-10568](https://issues.sonatype.org/browse/NEXUS-10568) they mention that it is being looked at but as far as I can see it has not been resolved.

Can someone please verify and comment?

**Comment by andy-ms** [comment]
The example there uses `@types/colors@0.6.29`. I don't think we can do anything to fix an old version. Do you have any package whose *latest* version doesn't work for you?

**Comment by mmckenziedev** [comment]
@andy-ms This looks more like a problem with my Nexus npm registry proxy. Nothing to do with you guys. Sorry to bother you.

**Pull request closed without merging**
