### PR TITLE
Fix semver bug when there is a prerelease tag

### PR DESCRIPTION
**Pull request by andy-ms**

### CODE REVIEW

**Comment by mhegazy** [comment]
👍

**Comment by thorn0** [comment]
Please rerun the publisher ASAP. Now it's impossible to install many packages that have `@types/node@4.0.*` as a dependency.

**Comment by mhegazy** [comment]
i am running it now. it is now processing packages with names starting with c's.  so should be done in the next few hours.

**Comment by mhegazy** [comment]
found another issue, republishing. third time is a charm.

**Pull request merged**
