### PR TITLE
Whitelist @storybook/react

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
DefinitelyTyped/DefinitelyTyped#38447 needs this

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Ping @sandersn @RyanCavanaugh

**Comment by orta** [comment]
Looks good to me - I wonder if _all_ of the packages will need to go in eventually. However right now this should be fine.

**Comment by MichaelDeBoey** [comment]
If so, I'll add a new PR for them 🙂

**Comment by MichaelDeBoey** [comment]
@orta I still get the error that `@storybook/react` isn't whitelisted.

Something I should do for that? 🤔

**Comment by orta** [comment]
Yeah, looks like making changes is a multi-step process, one of those steps is deploying a new version of this module - just waiting on https://github.com/microsoft/types-publisher/pull/659

**Comment by MichaelDeBoey** [comment]
@orta Can you deploy manually now so I can keep working on DefinitelyTyped/DefinitelyTyped#38447 please? 🤔

**Comment by orta** [comment]
Nope, sorry - I don't have access to that NPM module

**Comment by MichaelDeBoey** [comment]
Too bad 😕

Hopefully @sandersn or @RyanCavanaugh can make this happen quickly 🙂

**Comment by sandersn** [comment]
Deployment of types-publisher is not standard, but I think it only needs membership on the microsoft-internal typescript team. I went ahead and deployed it for now, and we can talk about reworking the deployment on #659.

Anyway, `@storybook/react` is now in the production branch, so Definitely Typed's CI will get the new whitelist next time it runs.

**Comment by MichaelDeBoey** [comment]
Thanks @sandersn! 🙂

**Pull request merged**
