### PR TITLE
Don't need `search-index-full.json` and `search-index-head.json`, so don't generate them.

### PR DESCRIPTION
**Pull request by andy-ms**
Depends on Microsoft/TypeSearch#13
The files would also have to be manually deleted from Azure.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
I'd prefer we keep the `-full` copy around just for debugging purposes. We can get rid of the other two, though

**Comment by andy-ms** [comment]
You mean get rid of just `-head`? `-full` is 11kb bigger than `-min` (see table in #86) so we probably want `-min` to be what TypeSearch accesses. Unless you think the difference isn't worth the complexity.

**Comment by RyanCavanaugh** [comment]
What I meant to say is that I want a file (maybe not a complete file) that has unminified field names in it. We don't have to upload it, just have it be an available artifact for someone to look at.

**Comment by andy-ms** [comment]
Maybe we could have a "--full" flag? Sounds like this is just for a command line users' testing?

**Comment by RyanCavanaugh** [comment]
Sure

**Comment by andy-ms** [comment]
OK, I've redone the entire PR. We now output `-full` as well when the user requests it. Also remembered to document this time.

**Comment by RyanCavanaugh** [comment]
:+1:

**Pull request merged**
