### PR TITLE
Add bookshelf to dependenciesWhitelist.txt for use in @types/bookshelf

### PR DESCRIPTION
**Pull request by jwhitmarsh**
I'm going to submit a PR to update @types/bookshelf to depend on [bookshelf](https://github.com/bookshel) rather than knex. This will ensure the types align more easily.

### CODE REVIEW

**Comment by jwhitmarsh** [comment]
Hi @sandersn, are you able to review this? Is there anything I can do to help?

**Comment by sandersn** [comment]
Sorry, I missed this before I went on vacation. 

Are you planning to remove bookshelf entirely? I’m not sure why you’d make bookshelf on DT depend on bookshelf itself, since it sounds like bookshelf ships its own types now. It might help to create the PR on DT to explain.

**Comment by jwhitmarsh** [comment]
Does bookshelf ship its own types? I can't find any types in the project, and if I remove @types/bookshelf from my project it won't build.

I would like @types/bookshelf to depend directly on bookshelf because that way it'll track bookshelf's knex version as it's updated - currently @types/bookshelf has to be updated as an extra step, which means in userland updating to new versions of bookshelf is always delayed until @types/bookshelf is updated. 

Apologies if i've explained that poorly - I've rewritten that paragraph a few times, so hopefully it's clear!

**Comment by sandersn** [comment]
OK, that *sort of* makes sense. :) I merged and updated types-publisher.

**Pull request merged**
